### PR TITLE
add AlertNotification Uid field

### PR DESCRIPTION
**Pull request by reugn**

### CODE REVIEW

**Comment by dw014081** [comment]
Would it be possible to get this PR merged and released anytime soon?

I need this enhancement so I can fix this issue[1] in the terraform-provider-grafana code base. I'm attempting to push dashboards with alerts into grafana and without the UID from alert-notification-channel I'm unable to fully automate the process.

Let me know what I can do to assist.

Thanks!


[1]  https://github.com/terraform-providers/terraform-provider-grafana/issues/83

**Comment by 58231** [comment]
I have a lot of Grafana automation that hinges on this. Can we get an approve please?

**Comment by lijok** [comment]
Any chance to get this merged in asap?
Impossible to set up alarms on panels with terraform without this

**Comment by giuliocalzolari** [comment]
any ETA?

**Comment by 58231** [comment]
Can we get a release cut?

**Pull request merged**
